services:

  mongodb:
    image: mongo:7
    container_name: freshlense-mongodb

    restart: unless-stopped

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_DATABASE: freshlense

    volumes:
      - mongo-data:/data/db

    healthcheck:
      test: ["CMD","mongosh","--eval","db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  backend:
    image: adityabawne37/freshlense-backend:latest
    container_name: freshlense-backend

    depends_on:
      mongodb:
        condition: service_healthy

    restart: unless-stopped

    expose:
      - "8000"

    environment:
      MONGO_URI: ${MONGO_URI}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      RESEND_API_KEY: ${RESEND_API_KEY}

    security_opt:
      - no-new-privileges:true

    cap_drop:
      - ALL

  frontend:
    image: adityabawne37/freshlense-frontend:latest
    container_name: freshlense-frontend

    depends_on:
      backend:
        condition: service_healthy

    restart: unless-stopped

    ports:
      - "80:80"

    environment:
      REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}

  prometheus:
    image: prom/prometheus:latest
    container_name: freshlense-prometheus

    restart: unless-stopped

    ports:
      - "9090:9090"

    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

    depends_on:
      backend:
        condition: service_healthy

volumes:
  mongo-data: