version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: freshlense-mongodb

    restart: unless-stopped

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_DATABASE: freshlense

    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend

    container_name: freshlense-backend

    depends_on:
      - mongodb

    ports:
      - "8000:8000"

    env_file:
      - .env.dev

  frontend:
    build:
      context: ./frontend

    container_name: freshlense-frontend

    ports:
     - "3000:3000"

    env_file:
      - .env.dev

    depends_on:
      - backend

volumes:
  mongo-data:
