services:

  mongodb:
    image: mongo:7
    container_name: freshlense-mongodb

    restart: unless-stopped

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_DATABASE: freshlense

    volumes:
      - mongo-data:/data/db

    healthcheck:
      test: ["CMD","mongosh","--eval","db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  backend:
    image: adityabawne37/freshlense-backend:latest
    container_name: freshlense-backend

    depends_on:
      mongodb:
        condition: service_healthy

    restart: unless-stopped

    read_only: true

    ports:
      - "8000:8000"

    environment:
      MONGO_URI: ${MONGO_URI}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      RESEND_API_KEY: ${RESEND_API_KEY}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}

    security_opt:
      - no-new-privileges:true

    cap_drop:
      - ALL

  frontend:
    image: adityabawne37/freshlense-frontend:latest
    container_name: freshlense-frontend

    depends_on:
      backend:
        condition: service_healthy

    restart: unless-stopped

    ports:
      - "80:80"

    environment:
      REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}

  prometheus:
    build:
      context: ./monitoring

    image: freshlense-prometheus:latest

    container_name: freshlense-prometheus

    restart: unless-stopped

    ports:
      - "9090:9090"

    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/rules:/etc/prometheus/rules:ro

    depends_on:
      backend:
        condition: service_healthy

  alertmanager:
    image: prom/alertmanager:latest
    container_name: freshlense-alertmanager

    restart: unless-stopped

    ports:
      - "9093:9093"

    volumes:
      - /home/adibawne37/jenkins_home/workspace/FreshLense-CD/monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro

    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: freshlense-node-exporter

    restart: unless-stopped

    ports:
      - "9100:9100"

    command:
      - "--path.rootfs=/host"

    volumes:
      - "/:/host:ro,rslave"

  grafana:
    image: grafana/grafana:latest
    container_name: freshlense-grafana

    restart: unless-stopped

    depends_on:
      - prometheus

    ports:
      - "3000:3000"

    volumes:
      - grafana-data:/var/lib/grafana

  loki:
    image: grafana/loki:latest
    container_name: freshlense-loki

    restart: unless-stopped

    ports:
      - "3100:3100"

    command: -config.file=/etc/loki/loki-config.yml

    volumes:
      - /home/adibawne37/jenkins_home/workspace/FreshLense-CD/monitoring/loki/loki-config.yml:/etc/loki/loki-config.yml:ro

  promtail:
    image: grafana/promtail:latest
    container_name: freshlense-promtail

    restart: unless-stopped

    command: -config.file=/etc/promtail/promtail-config.yml

    volumes:
      - /home/adibawne37/jenkins_home/workspace/FreshLense-CD/monitoring/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

    depends_on:
      - loki

volumes:
  mongo-data:
  grafana-data:
