name: FreshLense CI

on:
  push:
    branches:
      - main
      - freshlense-2.0
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            adityabawne37/freshlense-backend:latest
            adityabawne37/freshlense-backend:${{ github.sha }}

      - name: Build Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.prod
          push: true
          tags: |
            adityabawne37/freshlense-frontend:latest
            adityabawne37/freshlense-frontend:${{ github.sha }}